feat: Cerby-Veza connector
Veza/oaa-community pull request #79
Opened 2024-11-29 19:25 UTC by erikvilla

Adds Cerby-Veza connector to community connectors

2025-01-03 18:25 UTC, zkhoo-veza requested changes
Just a couple of items in the README but otherwise looks good.

2025-01-03 18:25 UTC, zkhoo-veza commented on connectors/cerby/README.md
> +## Notes
Looks like after using --sync-users and/or --sync-applications, you need to run --push. I suggest you call it out in the notes and/or explain why this option even exists at all.

2025-01-03 18:25 UTC, zkhoo-veza commented on connectors/cerby/README.md
> +| Cerby       | Generic Application |
Could be mistaken, but I think it should look like the below?

| Cerby          | OAA Custom Application Template |
| ----------- |---------------------|
| application | Custom Resource      |
| user            | Local User                  |

2025-01-08 16:25 UTC, erikvilla commented on connectors/cerby/README.md
> +## Notes
My bad I never filled the section

2025-01-09 22:06 UTC, zkhoo-veza approved these changes
LGTM

2025-01-09 22:07 UTC, merged